# Generated by Django 2.1.4 on 2019-02-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_media


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TCoreUserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cu_type', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('cu_super_set', models.CharField(choices=[('u', 'user'), ('g', 'group'), ('o', 'other')], max_length=1)),
                ('cu_phone_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('cu_alt_phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('cu_emp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('cu_profile_img', models.ImageField(default=None, upload_to=dynamic_media.get_directory_path)),
                ('cu_dob', models.DateField(blank=True, default=None, max_length=8, null=True)),
                ('cu_is_deleted', models.BooleanField(default=True)),
                ('cu_created_at', models.DateTimeField(auto_now_add=True)),
                ('cu_updated_at', models.DateTimeField(auto_now=True)),
                ('cu_deleted_at', models.DateTimeField(auto_now=True)),
                ('cu_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_created_by', to=settings.AUTH_USER_MODEL)),
                ('cu_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('cu_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_updated_by', to=settings.AUTH_USER_MODEL)),
                ('cu_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cu_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_user_details',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tcoreuserdetail',
            unique_together={('cu_emp_code', 'cu_phone_no')},
        ),
    ]
