# Generated by Django 2.1.4 on 2019-02-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_media


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TCoreFunctionalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfa_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cfa_parent_id', models.IntegerField(default=0)),
                ('cfa_is_deleted', models.BooleanField(default=False)),
                ('cfa_created_at', models.DateTimeField(auto_now_add=True)),
                ('cfa_updated_at', models.DateTimeField(auto_now=True)),
                ('cfa_deleted_at', models.DateTimeField(auto_now=True)),
                ('cfa_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfa_created_by', to=settings.AUTH_USER_MODEL)),
                ('cfa_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfa_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('cfa_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfa_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_functional_area',
            },
        ),
        migrations.CreateModel(
            name='TCoreLogicalAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cla_is_deleted', models.BooleanField(default=False)),
                ('cla_created_at', models.DateTimeField(auto_now_add=True)),
                ('cla_updated_at', models.DateTimeField(auto_now=True)),
                ('cla_deleted_at', models.DateTimeField(auto_now=True)),
                ('cla_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cla_created_by', to=settings.AUTH_USER_MODEL)),
                ('cla_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cla_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('cla_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cla_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_logical_areas',
            },
        ),
        migrations.CreateModel(
            name='TCoreModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cm_desc', models.TextField(blank=True, null=True)),
                ('cm_icon', models.ImageField(blank=True, default=None, null=True, upload_to=dynamic_media.get_directory_path)),
                ('cm_url', models.TextField(blank=True, null=True)),
                ('cm_is_deleted', models.BooleanField(default=False)),
                ('cm_is_editable', models.BooleanField(default=True)),
                ('cm_created_at', models.DateTimeField(auto_now_add=True)),
                ('cm_updated_at', models.DateTimeField(auto_now=True)),
                ('cm_deleted_at', models.DateTimeField(auto_now=True)),
                ('cm_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_created_by', to=settings.AUTH_USER_MODEL)),
                ('cm_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_modules',
            },
        ),
        migrations.CreateModel(
            name='TCoreOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cot_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cot_is_deleted', models.BooleanField(default=False)),
                ('cot_created_at', models.DateTimeField(auto_now_add=True)),
                ('cot_updated_at', models.DateTimeField(auto_now=True)),
                ('cot_deleted_at', models.DateTimeField(auto_now=True)),
                ('cot_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cot_created_by', to=settings.AUTH_USER_MODEL)),
                ('cot_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cot_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('cot_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cot_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_others',
            },
        ),
        migrations.CreateModel(
            name='TCorePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_u', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_g', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_o', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_created_at', models.DateTimeField(auto_now_add=True)),
                ('cp_updated_at', models.DateTimeField(auto_now=True)),
                ('cp_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cp_created_by', to=settings.AUTH_USER_MODEL)),
                ('cp_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cp_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_permissions',
            },
        ),
        migrations.CreateModel(
            name='TCoreRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cr_parent_id', models.IntegerField(default=0)),
                ('cr_is_deleted', models.BooleanField(default=False)),
                ('cr_created_at', models.DateTimeField(auto_now_add=True)),
                ('cr_updated_at', models.DateTimeField(auto_now=True)),
                ('cr_deleted_at', models.DateTimeField(auto_now=True)),
                ('cr_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cr_created_by', to=settings.AUTH_USER_MODEL)),
                ('cr_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cr_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('cr_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cr_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_roles',
            },
        ),
        migrations.AddField(
            model_name='tcoremodule',
            name='cm_permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_permissions', to='core.TCorePermissions'),
        ),
        migrations.AddField(
            model_name='tcoremodule',
            name='cm_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tcorepermissions',
            unique_together={('cp_u', 'cp_g', 'cp_o')},
        ),
    ]
