# Generated by Django 2.0.13 on 2019-03-04 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCoreUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_is_deleted', models.BooleanField(default=False)),
                ('c_created_at', models.DateTimeField(auto_now_add=True)),
                ('c_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_created_by', to=settings.AUTH_USER_MODEL)),
                ('c_owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_owned_by', to=settings.AUTH_USER_MODEL)),
                ('c_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_units',
            },
        ),
    ]
