# Generated by Django 2.0.13 on 2019-03-04 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import dynamic_media
import validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.BigIntegerField()),
                ('module_table_name', models.TextField(blank=True, null=True)),
                ('action_type', django_mysql.models.EnumField(choices=[('add', 'add'), ('edit', 'edit'), ('delete', 'delete')])),
                ('current_module_data', models.TextField(blank=True, null=True)),
                ('updated_module_data', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_log',
            },
        ),
        migrations.CreateModel(
            name='PmsTenderBidderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_type', django_mysql.models.EnumField(choices=[('joint_venture', 'joint_venture'), ('individual', 'individual')])),
                ('type_of_partner', models.IntegerField(blank=True, choices=[(1, 'lead_partner'), (2, 'other_partner')], null=True)),
                ('responsibility', django_mysql.models.EnumField(blank=True, choices=[('technical', 'technical'), ('financial', 'financial'), ('technical_and_financial', 'technical_and_financial')], null=True)),
                ('profit_sharing_ratio_actual_amount', models.FloatField(blank=True, default=None, null=True)),
                ('profit_sharing_ratio_tender_specific_amount', models.FloatField(blank=True, default=None, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_b_t_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_b_t_owned_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_bidder_type',
            },
        ),
        migrations.CreateModel(
            name='PmsTenderBidderTypeVendorMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_b_t_v_m_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_b_t_v_m_owned_by', to=settings.AUTH_USER_MODEL)),
                ('tender_bidder_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.PmsTenderBidderType')),
            ],
            options={
                'db_table': 'pms_tender_bidder_type_vendor_mapping',
            },
        ),
        migrations.CreateModel(
            name='PmsTenderDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tender_document', models.FileField(blank=True, default=None, null=True, upload_to=dynamic_media.get_directory_path, validators=[validators.validate_file_extension])),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_d_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_d_owned_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_documents',
            },
        ),
        migrations.CreateModel(
            name='PmsTenderEligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', django_mysql.models.EnumField(choices=[('technical', 'technical'), ('financial', 'financial'), ('special', 'special')])),
                ('ineligibility_reason', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_e_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_e_owned_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_eligibility',
            },
        ),
        migrations.CreateModel(
            name='PmsTenderEligibilityFieldsByType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.TextField(blank=True, null=True)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('eligible', models.BooleanField(default=False)),
                ('not_eligible', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_e_f_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_e_f_owned_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_eligibility_fields_by_type',
            },
        ),
        migrations.CreateModel(
            name='PmsTenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=50, unique=True)),
                ('tender_final_date', models.DateTimeField(blank=True, null=True)),
                ('tender_opened_on', models.DateTimeField(blank=True, null=True)),
                ('tender_added_by', models.CharField(blank=True, max_length=100, null=True)),
                ('tender_received_on', models.DateTimeField(blank=True, null=True)),
                ('tender_aasigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tenders',
            },
        ),
        migrations.CreateModel(
            name='PmsTenderVendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_v_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_v_owned_by', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_v_tender_id', to='pms.PmsTenders')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_v_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_vendors',
            },
        ),
        migrations.AddField(
            model_name='pmstendereligibilityfieldsbytype',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_e_f_tender_id', to='pms.PmsTenders'),
        ),
        migrations.AddField(
            model_name='pmstendereligibilityfieldsbytype',
            name='tender_eligibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_id', to='pms.PmsTenderEligibility'),
        ),
        migrations.AddField(
            model_name='pmstendereligibilityfieldsbytype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_e_f_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmstendereligibility',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_e_tender_id', to='pms.PmsTenders'),
        ),
        migrations.AddField(
            model_name='pmstendereligibility',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_e_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmstenderdocuments',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_d_tender_id', to='pms.PmsTenders'),
        ),
        migrations.AddField(
            model_name='pmstenderdocuments',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_d_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmstenderbiddertypevendormapping',
            name='tender_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.PmsTenderVendors'),
        ),
        migrations.AddField(
            model_name='pmstenderbiddertype',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_b_t_tender_id', to='pms.PmsTenders'),
        ),
        migrations.AddField(
            model_name='pmstenderbiddertype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_b_t_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
