# Generated by Django 2.0.13 on 2019-03-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmstenders',
            old_name='tender_id',
            new_name='tender_g_id',
        ),
    ]
