# Generated by Django 2.0.13 on 2019-03-04 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_media
import validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0002_auto_20190304_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsTenderSurveySitePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to=dynamic_media.get_directory_path, validators=[validators.validate_file_extension])),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_s_s_p_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_s_s_p_owned_by', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_s_s_p_tender_id', to='pms.PmsTenders')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_s_s_p_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_survey_site_photos',
            },
        ),
    ]
