# Generated by Django 2.0.13 on 2019-03-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_auto_20190304_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmstendersurveymaterials',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TCoreUnit'),
        ),
    ]
