# Generated by Django 2.0.13 on 2019-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_auto_20190305_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmstendersurveycoordinatessuppliers',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'raw_materials'), (2, 'crusher')], null=True),
        ),
    ]
