# Generated by Django 2.0.13 on 2019-03-06 07:52

from django.db import migrations, models
import dynamic_media
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_auto_20190306_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmstenderdocuments',
            name='tender_document',
            field=models.FileField(blank=True, default=None, null=True, upload_to=dynamic_media.get_directory_path, validators=[validators.validate_file_extension]),
        ),
    ]
