# Generated by Django 2.0.13 on 2019-03-06 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_media
import validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0010_auto_20190306_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsTenderInitialCosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('tender_notice_no_bid_id_no', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_work', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to=dynamic_media.get_directory_path, validators=[validators.validate_file_extension])),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_owned_by', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_tender_id', to='pms.PmsTenders')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_initial_costing',
            },
        ),
        migrations.CreateModel(
            name='PmsTenderInitialCostingExcelFieldLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_e_f_l_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_e_f_l_owned_by', to=settings.AUTH_USER_MODEL)),
                ('tender_initial_costing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_e_f_l_costing_id', to='pms.PmsTenderInitialCosting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_e_f_l_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_initial_costing_excel_field_label',
            },
        ),
        migrations.CreateModel(
            name='PmsTenderInitialCostingExcelFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_e_f_v_created_by', to=settings.AUTH_USER_MODEL)),
                ('field_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_e_f_l_label_id', to='pms.PmsTenderInitialCostingExcelFieldLabel')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_e_f_v_owned_by', to=settings.AUTH_USER_MODEL)),
                ('tender_initial_costing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_e_f_v_costing_id', to='pms.PmsTenderInitialCosting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_i_c_e_f_v_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_initial_costing_excel_field_value',
            },
        ),
    ]
