# Generated by Django 2.0.13 on 2019-03-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_auto_20190306_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmstendereligibility',
            name='eligibility_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='pmstendereligibility',
            unique_together={('type', 'tender')},
        ),
    ]
