# Generated by Django 2.0.13 on 2019-03-07 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_media
import validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0013_auto_20190307_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsTenderTabDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date_o_s', models.DateField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tab_document', models.FileField(blank=True, default=None, null=True, upload_to=dynamic_media.get_directory_path, validators=[validators.validate_file_extension])),
                ('is_upload_document', models.BooleanField(default=False)),
                ('reason_for_no_documentation', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_t_d_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_t_d_owned_by', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_t_d_tender_id', to='pms.PmsTenders')),
                ('tender_eligibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_t_d_eligibility_id', to='pms.PmsTenderEligibility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_t_d_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_tab_documents',
            },
        ),
        migrations.CreateModel(
            name='PmsTenderTabDocumentsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date_o_s', models.DateField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tab_document', models.FileField(blank=True, default=None, null=True, upload_to=dynamic_media.get_directory_path, validators=[validators.validate_file_extension])),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_t_d_p_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_t_d_p_owned_by', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_t_d_p_tender_id', to='pms.PmsTenders')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_t_d_p_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_tender_tab_documents_price',
            },
        ),
    ]
