# Generated by Django 2.0.13 on 2019-03-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_pmstendertabdocuments_pmstendertabdocumentsprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmstendereligibilityfieldsbytype',
            name='not_eligible',
        ),
        migrations.AlterField(
            model_name='pmstendereligibilityfieldsbytype',
            name='eligible',
            field=models.BooleanField(default=True),
        ),
    ]
