# Generated by Django 2.0.13 on 2019-03-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0015_auto_20190308_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmstenderinitialcosting',
            old_name='total_amount',
            new_name='difference_in_budget',
        ),
        migrations.AddField(
            model_name='pmstenderinitialcosting',
            name='quoted_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmstenderinitialcosting',
            name='received_estimate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
