# Generated by Django 2.0.13 on 2019-03-12 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0016_auto_20190308_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsAttandanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pms_attandance_log',
            },
        ),
        migrations.CreateModel(
            name='PmsAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'individual'), (2, ' labours under individual')], null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('login_latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('login_longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('login_address', models.TextField(blank=True, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('logout_latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('logout_longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('logout_address', models.TextField(blank=True, null=True)),
                ('approved_status', models.IntegerField(blank=True, choices=[(1, 'pending'), (2, 'approved'), (3, 'reject')], null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attandance_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attandance_employee_id', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attandance_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attandance_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_attandance',
            },
        ),
        migrations.CreateModel(
            name='PmsProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_owned_by', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_tender_id', to='pms.PmsTenders')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_projects',
            },
        ),
        migrations.AddField(
            model_name='pmsattandancelog',
            name='attandance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_l_attandance_id', to='pms.PmsAttendance'),
        ),
        migrations.AddField(
            model_name='pmsattandancelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_l_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmsattandancelog',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_l_owned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
