# Generated by Django 2.0.13 on 2019-03-14 05:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_media
import validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0017_auto_20190312_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsExternalUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('docfile_name', models.CharField(blank=True, max_length=200, null=True)),
                ('docfile', models.FileField(blank=True, default=None, null=True, upload_to=dynamic_media.get_directory_path, validators=[validators.validate_file_extension])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_users_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_users_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_users_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_external_userso',
            },
        ),
        migrations.CreateModel(
            name='PmsExternalUsersType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=200, null=True)),
                ('type_desc', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_users_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_users_type_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_users_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_external_users_type',
            },
        ),
        migrations.CreateModel(
            name='PmsMachineries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment_type', models.IntegerField(blank=True, choices=[(1, 'heavy_machinery'), (2, 'light_machinery')], null=True)),
                ('owner_type', models.IntegerField(blank=True, choices=[(1, 'rental'), (2, 'own')], null=True)),
                ('equipment_company', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment_model_no', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment_registration_no', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment_power', models.CharField(blank=True, max_length=200, null=True)),
                ('measurement_by', models.IntegerField(blank=True, choices=[(1, 'distance'), (2, 'time')], null=True)),
                ('measurement_quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment_price', models.FloatField(blank=True, null=True)),
                ('equipment_purchase_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_machineries',
            },
        ),
        migrations.CreateModel(
            name='PmsMachineriesWorkingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineries_working_category_created_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineries_working_category_owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineries_working_category_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pms_machineries_working_category',
            },
        ),
        migrations.AddField(
            model_name='pmsmachineries',
            name='equipment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_working_category', to='pms.PmsMachineriesWorkingCategory'),
        ),
        migrations.AddField(
            model_name='pmsmachineries',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_owned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmsmachineries',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmsexternalusers',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_users_type', to='pms.PmsExternalUsersType'),
        ),
    ]
