# Generated by Django 2.0.13 on 2019-03-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0018_auto_20190314_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmsmachineries',
            old_name='equipment_company',
            new_name='equipment_make',
        ),
    ]
