# Generated by Django 2.0.13 on 2019-03-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_auto_20190314_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsmachineries',
            name='equipment_last_pm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmsmachineries',
            name='equipment_next_pm_schedule',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmsmachineries',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
