# Generated by Django 2.1.4 on 2019-02-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TCoreFunctionalAreaMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_is_deleted', models.BooleanField(default=False)),
                ('fam_created_at', models.DateTimeField(auto_now_add=True)),
                ('fam_updated_at', models.DateTimeField(auto_now=True)),
                ('fam_deleted_at', models.DateTimeField(auto_now=True)),
                ('fam_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fam_created_by', to=settings.AUTH_USER_MODEL)),
                ('fam_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fam_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('fam_functional_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_functional_area', to='core.TCoreFunctionalArea')),
                ('fam_mmfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_mmfa', to='master.TMasterModuleFunctionalArea')),
                ('fam_permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_permissions', to='core.TCorePermissions')),
                ('fam_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fam_updated_by', to=settings.AUTH_USER_MODEL)),
                ('fam_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_functional_area_meta',
            },
        ),
        migrations.CreateModel(
            name='TCoreLogicalAreasMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lam_is_deleted', models.BooleanField(default=False)),
                ('lam_created_at', models.DateTimeField(auto_now_add=True)),
                ('lam_updated_at', models.DateTimeField(auto_now=True)),
                ('lam_deleted_at', models.DateTimeField(auto_now=True)),
                ('lam_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lam_created_by', to=settings.AUTH_USER_MODEL)),
                ('lam_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lam_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('lam_logical_areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lam_logical_areas', to='core.TCoreLogicalAreas')),
                ('lam_mmla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lam_mmla', to='master.TMasterModuleLogicalAreas')),
                ('lam_permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lam_permissions', to='core.TCorePermissions')),
                ('lam_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lam_updated_by', to=settings.AUTH_USER_MODEL)),
                ('lam_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lam_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_logical_areas_meta',
            },
        ),
        migrations.CreateModel(
            name='TCoreUserMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um_is_deleted', models.BooleanField(default=False)),
                ('um_created_at', models.DateTimeField(auto_now_add=True)),
                ('um_updated_at', models.DateTimeField(auto_now=True)),
                ('um_deleted_at', models.DateTimeField(auto_now=True)),
                ('um_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='um_created_by', to=settings.AUTH_USER_MODEL)),
                ('um_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='um_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('um_fa_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='um_fa_meta', to='meta.TCoreFunctionalAreaMeta')),
                ('um_la_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='um_la_meta', to='meta.TCoreLogicalAreasMeta')),
                ('um_mmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='um_mmo', to='master.TMasterModuleOther')),
                ('um_mmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='um_mmr', to='master.TMasterModuleRole')),
                ('um_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='um_role', to='core.TCoreModule')),
                ('um_other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='um_other', to='core.TCoreOther')),
                ('um_permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='um_permissions', to='core.TCorePermissions')),
                ('um_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='um_updated_by', to=settings.AUTH_USER_MODEL)),
                ('um_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='um_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_core_user_meta',
            },
        ),
    ]
