# Generated by Django 2.1.4 on 2019-02-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TMasterModuleFunctionalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmfa_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mmfa_functional_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmfa_functional_area', to='core.TCoreFunctionalArea')),
                ('mmfa_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmfa_module', to='core.TCoreModule')),
            ],
            options={
                'db_table': 't_master_module_functional_area',
            },
        ),
        migrations.CreateModel(
            name='TMasterModuleLogicalAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmla_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mmla_logical_areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmla_logical_areas', to='core.TCoreLogicalAreas')),
                ('mmla_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmla_module', to='core.TCoreModule')),
            ],
            options={
                'db_table': 't_master_module_logical_areas',
            },
        ),
        migrations.CreateModel(
            name='TMasterModuleOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mmo_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmo_module', to='core.TCoreModule')),
                ('mmo_other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmo_other', to='core.TCoreOther')),
            ],
            options={
                'db_table': 't_master_module_other',
            },
        ),
        migrations.CreateModel(
            name='TMasterModuleRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmr_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmr_module', to='core.TCoreModule')),
                ('mmr_permissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmr_permissions', to='core.TCorePermissions')),
                ('mmr_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmr_role', to='core.TCoreRole')),
                ('mmr_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmr_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_master_module_role',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tmastermodulerole',
            unique_together={('mmr_module', 'mmr_role', 'mmr_user')},
        ),
    ]
